name: Fac Habitat Scraper

on:
  schedule:
    # Runs every day at 9am, 3pm and 9pm
    - cron: '0 9,15,21 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google.list
        apt-get update
        apt-get install -y google-chrome-stable

    - name: Run scraper
      env:
        EMAIL_USER: ${{ secrets.MAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.MAIL_TO }}
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add availability_status.json
        git commit -m "Update availability status [$(date)]" || echo "No changes to commit"
        git push